# Generated by Django 3.1.1 on 2020-09-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0002_auto_20200930_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='kwh',
            field=models.FloatField(max_length=8),
        ),
    ]
