# Generated by Django 3.1.1 on 2020-10-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0008_auto_20201004_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overall_loss',
            name='T_D',
        ),
        migrations.RemoveField(
            model_name='overall_loss',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='overall_loss',
            name='energy_billed',
        ),
        migrations.RemoveField(
            model_name='overall_loss',
            name='month',
        ),
        migrations.RemoveField(
            model_name='overall_loss',
            name='sdo',
        ),
    ]
