# Generated by Django 3.1.1 on 2020-10-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0009_auto_20201005_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Overall_loss',
        ),
    ]
