# Generated by Django 3.1.1 on 2020-10-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0010_delete_overall_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='kwh',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
