# Generated by Django 3.1.1 on 2020-10-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0011_auto_20201005_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billed_unit',
            name='ht',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='billed_unit',
            name='lt',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='billed_unit',
            name='total',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='kwh',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='eht_consumer_unit',
            name='billed_unit',
            field=models.FloatField(max_length=5),
        ),
    ]
