# Generated by Django 3.1.1 on 2020-10-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0013_auto_20201006_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overall_loss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('sdo', models.CharField(max_length=10)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loss', models.FloatField(max_length=5)),
            ],
        ),
    ]
