# Generated by Django 3.1.1 on 2020-10-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0014_overall_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overall_loss',
            name='loss',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
