# Generated by Django 3.1.1 on 2020-10-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0015_auto_20201006_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billed_unit',
            name='ht',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billed_unit',
            name='lt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billed_unit',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eht_consumer_unit',
            name='billed_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
