# Generated by Django 3.1.1 on 2020-10-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0016_auto_20201006_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billed_unit',
            name='ht',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='billed_unit',
            name='lt',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='billed_unit',
            name='total',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='eht_consumer_unit',
            name='billed_unit',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='overall_loss',
            name='loss',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='overall_loss',
            name='sale',
            field=models.IntegerField(max_length=10),
        ),
    ]
