# Generated by Django 3.1.1 on 2020-10-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0017_auto_20201006_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overall_loss',
            name='consumption',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='overall_loss',
            name='loss',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='overall_loss',
            name='sale',
            field=models.CharField(max_length=10),
        ),
    ]
