# Generated by Django 3.1.1 on 2020-10-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0018_auto_20201006_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Overall_loss',
        ),
    ]
