# Generated by Django 3.1.1 on 2020-10-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0019_delete_overall_loss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vigilance_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('sdo', models.CharField(max_length=20)),
                ('billed_unit', models.IntegerField(max_length=10)),
            ],
        ),
    ]
