# Generated by Django 3.1.1 on 2020-10-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0020_vigilance_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vigilance_data',
            old_name='billed_unit',
            new_name='unit',
        ),
    ]
