# Generated by Django 3.1.1 on 2020-10-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0021_auto_20201007_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigilance_data',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
