# Generated by Django 3.1.1 on 2020-10-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0022_auto_20201007_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigilance_data',
            name='unit',
            field=models.IntegerField(max_length=10),
        ),
    ]
