# Generated by Django 3.1.1 on 2020-10-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0023_auto_20201009_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.FileField(blank=True, upload_to='post_image')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
