# Generated by Django 3.1.1 on 2020-10-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss', '0026_auto_20201012_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='billed_unit',
            name='sl_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='consumption',
            name='sl_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='eht_consumer_unit',
            name='sl_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vigilance_data',
            name='sl_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='billed_unit',
            name='ht',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billed_unit',
            name='lt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billed_unit',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='kwh',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eht_consumer_unit',
            name='billed_unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vigilance_data',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
